### ISSUE TITLE
Improve efficiency of theme/extension

### ISSUE THREAD

**Issue by AshleyHenry15** [posit-dev/product-doc-theme#6]
One you install the extension, there are several additional/manual steps that one must take to add things like:
- favicon
- header/nav entries
- footer
- link external icon
- link external new window
- toc: true
- etc.

See example below:
```
website:
  title: 
  favicon: "assets/images/favicon.svg"
  bread-crumbs: true
  navbar:
    pinned: true
    logo: "images/posit-icon-fullcolor.svg"
    logo-alt: "Posit documentation"  
  sidebar:
    style: "floating"
    collapse-level: 1
    search: true
    pinned: false
  page-footer:
    left: 
      - text: <img src='assets/images/posit-logo-black-TM.svg' id='footer-logo'> © 2024 Posit Software, PBC formerly RStudio, PBC 
        url: "https://posit.co/"
    center: |
      Posit Product 12345 

    right:
      - icon: book
        href: https://docs.posit.co/
      - icon: question-circle-fill
        href: https://support.posit.co/hc/en-us
      - icon: lightbulb-fill
        href: https://solutions.posit.co/

format:
  html:
    theme: 
      - _extensions/posit-dev/posittheme/theme.scss
    link-external-icon: true
    link-external-newwindow: true
    toc: true
    toc-expand: true
```

I am manually sending this block to people vs. some of these entries being applied automatically. This kind of "undoes" some of the efficiency of having a "default theme".

@edavidaja had mentioned:
>_extensions subdirectory for the theme, it could be set up so that
    ```format:
             posit-docs-html: default
    ```

Looking for ways to improve this and remove some of the manual steps that need to be taken to align the sites.
